### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by 256dpi** [256dpi/fire-auth#1]
Auth
- [ ] Refresh token support
- [ ] Authorization code support (explicit grant)

Documentation
- [ ] Custom AccessToken Generation
- [ ] Authorize & GinAuthorizer
